defaults:
  - params_schema

_target_: "params.HFParams"
gen_kwargs: {
  "temperature": 0.1,
  "return_full_text": False,
  "do_sample": True,
  "top_k": 50,
  "top_p": 1.0,
  "num_beams": 1,}
  
name: "beams=${str:${model.params.gen_kwargs.num_beams}}_temp=${str:${model.params.gen_kwargs.temperature}}_topk=${str:${model.params.gen_kwargs.top_k}}_topp=${str:${model.params.gen_kwargs.top_p}}"